### ISSUE TITLE
Add a configuration plugins maybe / Only executable with Live serveur

### ISSUE THREAD

**Issue by DefCrotype** [Ouo-droid/ToDoList-Kanban#1]
The execution is only available with Live serveur when drag and drop, 
[Error] Failed to load resource: Origin null is not allowed by Access-Control-Allow-Origin. Status code: 0 (main.js, line 0);

**Comment by Ouo-droid** [comment]
No need of CORS method only pass by live serveur,

Sincerely

**Comment by DefCrotype** [comment]
Thanks
